const MainData = {
  main: {
    src:
      "https://www.yuca.tv/custom/celine/player.php?uid=ebdbb4eb-4586-5873-abb3-aa161bf8b0b1&lang=en&type=standard&loop=true&mute=true&autorun=true&_=0.5787494838904113",
    description:
      'CELINE HOMME\nTHE DANCING KID\nCIRCUIT DU CASTELLET, FRANCE\nJULY 13TH 2020\n\nMUSIC ORIGINAL SOUNDTRACK FOR CELINE\n "THEY CALL ME TIAGO (THE DANCING KID CELINE EDIT)"PERFORMED BY TIAGZ\nCOURTESY OF EPIC RECORDS BY ARRANGEMENT WITH SONY MUSIC ENTERTAINMENT\n\nSTYLING AND DIRECTING "THE DANCING KID"\n EDI SLIMANE\n\nMAKE-UP ARTIST\nCHRISTELLE COCQUET\n\nHAIRSTYLISTS\nESTHER LANGHAM AND ALEX BROWNSELL \n\n',
  },
};

export default MainData;
