const MainData = {
  main: {
    src:
      "https://www.yuca.tv/custom/celine/player.php?uid=ebdbb4eb-4586-5873-abb3-aa161bf8b0b1&lang=en&type=standard&loop=true&mute=true&autorun=true&_=0.5787494838904113",
    description:
      'CELINE HOMME\nTHE DANCING KID\nCIRCUIT DU CASTELLET, FRANCE\nJULY 13TH 2020\n\nMUSIC ORIGINAL SOUNDTRACK FOR CELINE\n "THEY CALL ME TIAGO (THE DANCING KID CELINE EDIT)"PERFORMED BY TIAGZ\nCOURTESY OF EPIC RECORDS BY ARRANGEMENT WITH SONY MUSIC ENTERTAINMENT\n\nSTYLING AND DIRECTING "THE DANCING KID"\n EDI SLIMANE\n\nMAKE-UP ARTIST\nCHRISTELLE COCQUET\n\nHAIRSTYLISTS\nESTHER LANGHAM AND ALEX BROWNSELL \n\n',
  },
  winter2020: {
    src:
      "https://www.yuca.tv/en/embed/5d44ee6f2c3f71b73125876103c8f6c4?mute=true&autorun=true&_=0.11945388741015517",
    description:
      "CELINE\n06\nWINTER 20\nLES INVALIDES, 28 FEBRUARY 2020\n\n\nMUSIC ORIGINAL SOUNDTRACK FOR CELINE\nSOFIA BOLT “GET OUT OF MY HEAD”\nWRITTEN AND COMPOSED BY SOFIA BOLT\n\n\nSTYLING AND SET DESIGN\nHEDI SLIMANE",
  },
};

export default MainData;
