import React, { Component } from "react";

class ProductDetails extends Component {
  render() {
    return (
      <div className="ProductDetails">
        <h1>care and maintenance</h1>
        <p>
          FOR YOUR SHOES, CELINE HAS SELECTED THE HIGHEST QUALITY HIDES. THEY
          ARE UNIQUE: VARIATIONS IN COLOUR, SMALL MARKS AND VEINS ARE NATURAL
          FEATURES AND SHOULD NOT BE CONSIDERED IMPERFECTIONS. THE METAL PARTS
          WERE SELECTED FOR THEIR QUALITY AND WILL DEVELOP A PATINA OVER TIME.
        </p>
        <p>
          TO KEEP YOUR SHOES LOOKING THEIR BEST OVER TIME, WE RECOMMEND THE
          FOLLOWING INSTRUCTIONS:
        </p>
        <p>
          - AVOID CONTACT WITH WATER, GREASE, PERFUME AND COSMETICS. DRY DAMP
          SHOES WITH A SOFT, LIGHT-COLOURED CLOTH TO ABSORB ANY LIQUID.
        </p>
        <p>- AVOID PROLONGED EXPOSURE TO HEAT AND STRONG SOURCES OF LIGHT.</p>
        <p>- SCRATCHES ON SOME LEATHERS CAN BE REDUCED WITH GENTLE RUBBING.</p>
        <p>
          - IF YOUR HEELS OR SOLES HAVE WORN OUT, TAKE YOUR SHOES TO A
          SPECIALIST WHO CAN REHEEL THEM OR ADD THIN RUBBER SOLES.
        </p>
        <p>
          - TO CLEAN YOUR SHOES, WIPE THEM CAREFULLY USING A CLEAN, SOFT CLOTH
          THAT IS LEFT DRY FOR LEATHER OR SLIGHTLY MOISTENED FOR FABRIC. WHEN
          YOU ARE NOT WEARING YOUR SHOES, WE RECOMMEND STORING THEM IN THEIR
          INDIVIDUAL POUCHES INSIDE THE BOX.
        </p>
      </div>
    );
  }
}

export default ProductDetails;
