const MenuData = {
  "celine women": {
    "new winter part 1": [],
    "charms collection": [],
    "ready to wear": [
      "dress & skrts",
      "kackets & coats",
      "knitwear",
      "shirts & blouses",
      "pants",
      "leather & fur",
      "denum",
      "t-shirts & sweatshirts",
    ],
    shoes: [
      "boots",
      "wedges",
      "espadrilles",
      "clogs",
      "flats",
      "sandals",
      "pumps",
      "sneakers",
    ],
    handbags: [
      "new",
      "16",
      "triomphe",
      "triomphe canvas",
      "luggage",
      "classic",
      "belt bag",
      "more lines",
    ],
    "small leather goods": [
      "new",
      "wallets",
      "card holders",
      "clutches",
      "tech accessories",
      "more",
    ],
    jewellery: ["fine jewellery", "jewellery"],
    accessories: [
      "new",
      "charms",
      "sunglasses",
      "hats",
      "soft accessories",
      "belts",
      "tech accessories",
      "collection celine masion",
    ],
  },
  "celine men": [],
  "celine haute parfumerie": [],
  "celine collections": {
    "men's summer 2021": ["show", "runway looks", "teaser 01", "teaser 02"],
    "winter 2020": [
      "show",
      "runway looks",
      "women's collection campaign",
      "men's collection campaign",
    ],
    "women's summer 2020": ["show", "runway looks", "campaign"],
    "men's summer 2020": ["show", "runway looks", "campaign"],
    "women's winter 2019": ["show", "runway looks", "campaign"],
    "men's winter 2019": ["show", "runway looks", "campaign"],
    "summer 2019": [
      "show",
      "runway looks",
      "women's collection campaign",
      "men's collection campaign",
    ],
    "introduction campaign": ["part 1", "part 2"],
  },
  "celine maison de couture": {
    "16 vivienne": [],
    "artistic projects": ["christian marclay"],
  },
};

export default MenuData;
